//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstExampleCURD1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public long EmpId { get; set; }
        public string EmpName { get; set; }
        public string Mob { get; set; }
        public Nullable<long> DeptId { get; set; }
        public Nullable<long> AreaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Dept Dept { get; set; }
    }
}
