//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emptb1
    {
        public long EmpId { get; set; }
        public string EmpName { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string DeptName { get; set; }
        public string Salary { get; set; }
    }
}
